name: multi-MTRB
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - python-dotenv
  - remotezip
  - tqdm
  - pyyaml
  - scikit-learn
  - pandas>=2.2.0
  - numpy>=2.1.0
  - accelerate>=1.2.0
  - transformers>=4.48.0
  - sentencepiece
  - protobuf
  - tiktoken
  - matplotlib
  - seaborn
  - structlog
  - pytest
  - pytest-cov
  - pytorch-metric-learning
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch
      - torchvision
      - torchaudio

