name: multi-MTRB
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - tqdm
  - pyyaml
  - scikit-learn
  - pandas>=2.2.0
  - numpy>=2.1.0
  - accelerate>=1.2.0
  - transformers>=4.48.0
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu130
      - torch==2.10.0+cu130
      - torchvision==0.25.0+cu130
      - torchaudio==2.10.0+cu130

